language: java
script: mvn clean package -Djava.net.preferIPv4Stack=true 
jdk:
  - oraclejdk8

sudo: required

env:
  global:
    - PROJECT_ID="future-finance-157420"
    - NAME="mid-tier"

services:
  - docker

# as the cloud account is no longer active the stuff regarding that is is commented out

#before_install:
#  - openssl aes-256-cbc -K $encrypted_f4704c6cf078_key -iv $encrypted_f4704c6cf078_iv -in FutureFinance-9562e6d23f91.json.enc -out FutureFinance-9562e6d23f91.json -d
#  - gcloud auth activate-service-account --key-file FutureFinance-9562e6d23f91.json

install:
#  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
#  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
#  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
#  - sudo apt-get update && sudo apt-get install google-cloud-sdk kubectl
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$PWD/apache-maven-3.5.0/bin:$PATH

# after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#      docker build -t $NAME -t gcr.io/$PROJECT_ID/$NAME:$TRAVIS_COMMIT .;
#    fi

#deploy:
#  provider: script
#  script: scripts/deploy.sh gcr.io/$PROJECT_ID/$NAME:$TRAVIS_COMMIT
#  on:
#    branch: master

cache:
  directories:
    - $HOME/.m2
